# Generated by Django 4.2.5 on 2023-11-15 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_conted_view_post_created_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_date']},
        ),
    ]
