# Generated by Django 4.2.5 on 2024-04-08 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0010_alter_post_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="page_titel",
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="published",
            field=models.BooleanField(default=False),
        ),
    ]
