# Generated by Django 4.2.5 on 2024-04-08 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0013_rename_published_first_page_post_first_page_published"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="brand",
            field=models.CharField(max_length=30, null=True),
        ),
    ]
