# Generated by Django 4.2.5 on 2024-04-15 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0014_post_brand"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={"ordering": ["-create_date"]},
        ),
    ]
